# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BirthdayBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, date_of_birth: date = None):  # noqa: E501
        """BirthdayBody - a model defined in Swagger

        :param date_of_birth: The date_of_birth of this BirthdayBody.  # noqa: E501
        :type date_of_birth: date
        """
        self.swagger_types = {
            'date_of_birth': date
        }

        self.attribute_map = {
            'date_of_birth': 'dateOfBirth'
        }
        self._date_of_birth = date_of_birth

    @classmethod
    def from_dict(cls, dikt) -> 'BirthdayBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The birthday_body of this BirthdayBody.  # noqa: E501
        :rtype: BirthdayBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date_of_birth(self) -> date:
        """Gets the date_of_birth of this BirthdayBody.


        :return: The date_of_birth of this BirthdayBody.
        :rtype: date
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: date):
        """Sets the date_of_birth of this BirthdayBody.


        :param date_of_birth: The date_of_birth of this BirthdayBody.
        :type date_of_birth: date
        """
        if date_of_birth is None:
            raise ValueError("Invalid value for `date_of_birth`, must not be `None`")  # noqa: E501

        self._date_of_birth = date_of_birth
